# permissions for end users to view deployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-viewer-role
rules:
- apiGroups:
  - edge.mv.io
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - edge.mv.io
  resources:
  - deployments/status
  verbs:
  - get
